name: Random Daily Trigger API Caller

on:
  schedule:
    - cron: "0 15 * * *" # UTC

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Wait Random Time
        run: |
          # Calculate random delay between 15:00 and 15:30
          random_delay=$((RANDOM % 1800))
          echo "Waiting for $random_delay seconds..."
          sleep $random_delay

      - name: Call API
        run: curl "${{ secrets.NOTIFY_URL }}"
