name: Random Daily Trigger API Caller

on:
  schedule:
    - cron: "0 15 * * *" # UTC

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Convert to Norwegian Time & Wait Random Time
        run: |
          # Calculate random delay between 15:00 and 17:00
          max_wait_seconds=$(( (17 - 15) * 3600 )) # 2 hours in seconds
          random_delay=$((RANDOM % max_wait_seconds))
          echo "Waiting for $random_delay seconds..."
          sleep $random_delay

      - name: Call API
        run: curl "${{ secrets.NOTIFY_URL }}"
